# Rosé Pine Moon theme
term_background: 232136
term_foreground: C8C8E5
term_background_bright: 2A273F
term_foreground_bright: E0DEF4
term_palette: 232136;EB6F92;3E8FB0;F6C177;569FBA;C4A7E7;9CCFD8;C8C8E5
term_palette_bright: 2A273F;EB6F92;3E8FB0;F6C177;569FBA;C4A7E7;9CCFD8;E0DEF4

timeout: 3

/Artix Linux
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos
    cmdline: root=UUID=ed0ed4fc-3f2e-4084-96ca-1ff9dd18fd7c rw quiet
    module_path: boot():/amd-ucode.img
    module_path: boot():/initramfs-linux-cachyos.img
