#====================================================#
#                                                    #
#                picom.conf                          #
#                                                    #
#====================================================#

#################################
#             Shadows           #
#################################

shadow = false;
shadow-radius = 8;
shadow-opacity = .55;
shadow-offset-x = 0;
shadow-offset-y = 0;
shadow-color = "#191724";

#################################
#           Fading              #
#################################

fading = true;
fade-in-step = 0.043;
fade-out-step = 0.055;

#################################
#   Transparency / Opacity      #
#################################

# inactive-opacity-override removed (Deprecated)
frame-opacity = 0.7;

#################################
#           Corners             #
#################################

corner-radius = 8;

#################################
#            Blur               #
#################################

blur-kern = "3x3box";

#################################
#       General Settings        #
#################################

backend = "glx";
dithered-present = false;
vsync = true;

# mark-wmwin-focused removed (Deprecated)
# mark-ovredir-focused removed (Deprecated)

detect-rounded-corners = false;
detect-client-opacity = true;
use-ewmh-active-win = true;
unredir-if-possible = false;
detect-transient = true;
use-damage = true;
transparent-clipping = false;
log-level = "warn";

#################################
#             Rules             #
#################################

rules: (
  # Replacement for mark-wmwin-focused & mark-ovredir-focused
  {
    match = "true"; 
    focus = true;
  },

  # Replacement for inactive-opacity-override
  # This ensures windows maintain their own specified opacity
  {
    match = "true";
    opacity-modify = "inherit";
  },

  # Shadow Exclusions
  {
    match = "name = 'Notification'   || "
            "class_g = 'Conky'       || "
            "class_g = 'Notify-osd'  || "
            "class_g = 'Dunst'       || "
            "class_g = 'Cairo-clock' || "
            "class_g = 'fragments'   || "
            "class_g = 'Cider'       || "
            "class_g = 'easyeffects' || "
            "(class_g = 'firefox' && argb) || "
            "(class_g = 'firefoxdeveloperedition' && argb) || "
            "(class_g = 'xdg-desktop-portal-gnome' && window_type = 'menu') || "
            "_GTK_FRAME_EXTENTS@";
    shadow = false;
  },
  
  # Corner Radius Exclusions
  {
    match = "window_type = 'dock'    || "
            "window_type = 'desktop' || "
            "class_g = 'Polybar'     || "
            "class_g = 'Spotify'     || "
            "class_g = 'Inkscape'    || "
            "class_g = 'fragments'   || "
            "class_g = 'easyeffects' || "
            "class_g = 'krita'       || "
            "class_g = 'firefox'     || "
            "class_g = 'Vimb'        || "
            "class_g = 'Dunst'       || "
            "class_g = 'org.nicotine_plus.Nicotine' || "
            "class_g = 'kid3'        || "
            "class_g = 'qt5ct'       || "
            "class_g = 'Gucharmap'   || "
            "class_g = 'FFPWA-01JBC5V5SG3ZMGARGNPM7FS8HR'";
    corner-radius = 0;
  },

  # Focus Exclusions
  {
    match = "class_g = 'Cairo-clock'";
    focus = false;
  },

  # Modern Wintypes replacement
  {
    match = "window_type = 'tooltip'";
    fade = true;
    shadow = true;
    opacity = 1.0;
    focus = true;
    full-shadow = false;
  },
  {
    match = "window_type = 'dock'";
    shadow = false;
    clip-shadow-above = true;
  },
  {
    match = "window_type = 'dnd'";
    shadow = false;
  },
  {
    match = "window_type = 'popup_menu' || window_type = 'dropdown_menu'";
    opacity = 1.0;
  }
)
