Provider=stacked
SkipRecap=true
TrackingRemote=anilist
StoragePath=$HOME/.local/share/curd
ImagePreview=true
SubsLanguage=english
PercentageToMarkComplete=85
SkipFiller=true
NextEpisodePrompt=true
MyAnimeListClientSecret=
DiscordClientId=1287457464148820089
MyAnimeListClientID=f76d4c827152327b60654285d221222c
ScoreOnCompletion=true
MpvArgs=[]
TrackingConfigured=true
Player=mpv
MyAnimeListImported=false
ManualProviderSearch=false
SkipEd=true
DiscordPresence=true
DisabledProviders=[]
SaveMpvSpeed=true
MenuOrder=CURRENT,ALL,UNTRACKED,UPDATE,REMAP_PROVIDER,CONTINUE_LAST,TRACKER,PROVIDER
SubOrDub=sub
AlternateScreen=true
SubStyle=soft
RofiSelection=true
TrackingLocal=true
MyAnimeListImportDismissed=false
AnimeNameLanguage=english
SkipOp=true
AddMissingOptions=true
