## name: Rosé Pine
## upstream: https://github.com/rose-pine/amfora/blob/main/themes/rose-pine-moon.toml
## description: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

bg = "#232136"
tab_num = "#c4a7e7"
tab_divider = "#44415a"
bottombar_label = "#c4a7e7"
bottombar_text = "#c8c8e5"
bottombar_bg = "#2a273f"
scrollbar = "#2a283e"
hdg_1 = "#c4a7e7"
hdg_2 = "#9ccfd8"
hdg_3 = "#ea9a97"
amfora_link = "#f6c177"
foreign_link = "#908caa"
link_number = "#6e6a86"
regular_text = "#c8c8e5"
quote_text = "#c8c8e5"
preformatted_text = "#c8c8e5"
list_text = "#c8c8e5"
btn_bg = "#3e8fb0"
btn_text = "#c8c8e5"
dl_choice_modal_bg = "#2a273f"
dl_choice_modal_text = "#c8c8e5"
dl_modal_bg = "#2a273f"
dl_modal_text = "#c8c8e5"
info_modal_bg = "#2a273f"
info_modal_text = "#c8c8e5"
error_modal_bg = "#2a273f"
error_modal_text = "#eb6f92"
yesno_modal_bg = "#2a273f"
yesno_modal_text = "#c8c8e5"
tofu_modal_bg = "#2a273f"
tofu_modal_text = "#c8c8e5"
subscription_modal_bg = "#2a273f"
subscription_modal_text = "#c8c8e5"
input_modal_bg = "#2a273f"
input_modal_text = "#c8c8e5"
input_modal_field_bg = "#393552"
input_modal_field_text = "#c8c8e5"
bkmk_modal_bg = "#2a273f"
bkmk_modal_text = "#c8c8e5"
bkmk_modal_label = "#c4a7e7"
bkmk_modal_field_bg = "#393552"
bkmk_modal_field_text = "#c8c8e5"
