#[start]
#visual-home = "https://www.google.com/"

[buffer]
styling = true
scripting = true
images = true
autofocus = true

[display]
color-mode = "ansi"
format-mode = "auto"
image-mode = "kitty"
highlight-color = "eb6f92"  # pink highlight
highlight-marks = true
double-width-ambiguous = false
set-title = true

[page]
# Open current page in w3m for Google (text-only)
'g' = "pager.externFilterSource('w3m -dump \"$CHA_URL\"')"

# Open current page in rdrview for general text view
'r' = "pager.externFilterSource('rdrview -Hu \"$CHA_URL\"')"

# Format page text nicely
'f' = "pager.externFilterSource('fmt')"

# YouTube: allow scripting
[[siteconf]]
host = "https://www.youtube.com/"
scripting = true
styling = true

# Wikipedia: use vector skin
[[siteconf]]
url = '^https?://[a-z]+\.wikipedia\.org/wiki/(?!.*useskin=.*)'
rewrite-url = 'x => x.searchParams.append("useskin", "vector")'

# Google: optional site-specific config
[[siteconf]]
host = "https://www.google.com/"
scripting = true
styling = true
inline-css = """
body, html, input, textarea, select, button {
    background-color: #232136 !important;
    color: #c8c8e5 !important;
}

a {
    color: #9ccfd8 !important; /* blue links */
}

a:visited {
    color: #c4a7e7 !important; /* magenta visited links */
}

input, textarea {
    background-color: #393552 !important;
    color: #c8c8e5 !important;
    border-color: #6e6a86 !important;
}

div {
    background-color: transparent !important;
}
"""
# Uncomment if needed:
# Reddit
# [[siteconf]]
# host = "https://www.reddit.com/"
# scripting = true
# styling = true

# Instagram
# [[siteconf]]
# host = "https://www.instagram.com/"
# scripting = true
# styling = true
