#[start]
#visual-home = "https://www.google.com/"

[buffer]
images = true
autofocus = true

[display]
color-mode = "ansi"
format-mode = "auto"
image-mode = "kitty"
highlight-color = "eb6f92"
highlight-marks = true
double-width-ambiguous = false
set-title = true
default-background-color = "e0def4"
default-foreground-color = "232136"

[page]
' r' = "pager.externFilterSource('rdrview -Hu \"$CHA_URL\"')" 
' f' = "pager.externFilterSource('fmt')"

[css]
inline = """plaintext, pre { white-space: pre-wrap }"""

[[siteconf]]
#allow javascript YouTube
host = "https://www.youtube.com/"
scripting = true
styling = true
