#[start]
#visual-home = "https://www.google.com/"

[buffer]
styling = true
scripting = true
images = true
autofocus = true

[display]
color-mode = "ansi"
format-mode = "auto"
image-mode = "kitty"
highlight-color = "eb6f92"
highlight-marks = true
double-width-ambiguous = false
set-title = true
default-background-color = "c8c8e5"
default-foreground-color = "232136"

[page]
' r' = "pager.externFilterSource('rdrview -Hu \"$CHA_URL\"')" 
' f' = "pager.externFilterSource('fmt')"

[css]
inline = """plaintext, pre { white-space: pre-wrap }"""

# Allow javascript YouTube
[[siteconf]]
host = "https://www.youtube.com/"
scripting = true
styling = true

# Use the "vector" skin on Wikipedia. 
[[siteconf]]
url = '^https?://[a-z]+\.wikipedia\.org/wiki/(?!.*useskin=.*)'                                                              
rewrite-url = 'x => x.searchParams.append("useskin", "vector")' 

# Allow javascript + css Github
#[[siteconf]]
#host = "https://www.reddit.com/"
#scripting = true
#styling = true

# Allow javascript Instagram
#[[siteconf]]
#host = "https://www.instagram.com/"
#scripting = true
#styling = true

# Allow javascript Google
#[[siteconf]]
#host = "https://www.google.com/"
#scripting = true
#styling = true
