# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_size 12

# BEGIN_KITTY_FONTS
font_family      family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-Regular
bold_font        family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-Bold
italic_font      family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-Italic
bold_italic_font family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-SemiBoldItalic
# END_KITTY_FONTS

#: }}}

#: Cursor customization {{{

cursor_shape block
cursor_shape_unfocused hollow

cursor_trail 3
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0

#: }}}

#: Scrollback {{{

scrollback_lines 2000
scrollback_pager ~/.local/bin/kitty-pager
scrollback_pager_history_size 0

#: Scrollbar
scrollbar hovered

wheel_scroll_multiplier 5.0
touch_scroll_multiplier 1.0

#: }}}

#: Mouse {{{

url_style straight
open_url_with default
detect_urls yes
copy_on_select no
select_by_word_characters @-./_~?&=%+#
click_interval -1.0

#: }}}

#: Performance tuning {{{

repaint_delay 10
sync_to_monitor yes

#: }}}

#: Terminal bell {{{

enable_audio_bell yes
visual_bell_duration 0.0
window_alert_on_bell yes
bell_on_tab "🔔 "
linux_bell_theme freedesktop

#: }}}

#: Window layout {{{

remember_window_size  no
initial_window_width  640
initial_window_height 400
enabled_layouts *
window_resize_step_cells 1
window_resize_step_lines 1
window_border_width 1
draw_minimal_borders yes
window_padding_width 20 20 20 20
placement_strategy center
inactive_text_alpha 1.0
hide_window_decorations no

#: }}}

#: Tab bar {{{

tab_bar_edge              bottom
tab_bar_style             separator
tab_separator             ""
tab_bar_align             center
tab_bar_margin_height     10.0 6.0
tab_bar_margin_width      6.0

#: }}}

#: Color scheme {{{

include rose-pine-moon.conf

#: }}}

#: Advanced {{{

shell fish
close_on_child_death no
allow_remote_control yes
listen_on unix:@kitty
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
startup_session none
shell_integration enabled no-cursor
notify_on_cmd_finish invisible 15.0

term xterm-kitty

#: }}}

#: Keyboard shortcuts {{{

kitty_mod ctrl+shift
clear_all_shortcuts no

#: Clipboard {{{
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map cmd+v       paste_from_clipboard
map kitty_mod+s  paste_from_selection
map shift+insert paste_from_selection
#: }}}

#: Scrolling {{{
map kitty_mod+k     scroll_line_up
map kitty_mod+j       scroll_line_down
map kitty_mod+page_up scroll_page_up
map kitty_mod+page_down scroll_page_down
map kitty_mod+home scroll_home
map kitty_mod+end scroll_end
map kitty_mod+h show_scrollback
#: }}}

#: Window management {{{
map kitty_mod+enter new_window
map kitty_mod+n new_os_window
map kitty_mod+w close_window
map kitty_mod+] next_window
map kitty_mod+[ previous_window
map kitty_mod+f move_window_forward
map kitty_mod+b move_window_backward
map kitty_mod+` move_window_to_top
map kitty_mod+r start_resizing_window
map kitty_mod+1 first_window
map kitty_mod+2 second_window
map kitty_mod+3 third_window
map kitty_mod+4 fourth_window
map kitty_mod+5 fifth_window
map kitty_mod+6 sixth_window
map kitty_mod+7 seventh_window
map kitty_mod+8 eighth_window
map kitty_mod+9 ninth_window
map kitty_mod+0 tenth_window
#: }}}

#: Tab management {{{
map kitty_mod+right next_tab
map kitty_mod+left previous_tab
map kitty_mod+t new_tab
map kitty_mod+q close_tab
#: }}}

#: Layout management {{{
map kitty_mod+l next_layout
#: }}}

#: Font sizes {{{
map kitty_mod+equal  change_font_size all +2.0
map kitty_mod+minus       change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0
#: }}}

#: }}}
