## name: Rosé Pine Moon
## author: mvllow
## license: MIT
## upstream: https://github.com/rose-pine/kitty/blob/main/dist/rose-pine-moon.conf
## blurb: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

foreground               #c8c8e5
background               #232136
selection_foreground     #c8c8e5
selection_background     #44415a

cursor                   #56526e
cursor_text_color        #c8c8e5

url_color                #c4a7e7

active_tab_foreground    #232136
active_tab_background    #c4a7e7
inactive_tab_foreground  #232136
inactive_tab_background  #ea9a97

# black
color0   #393552
color8   #6e6a86

# red
color1   #eb6f92
color9   #eb6f92

# green
color2   #3e8fb0
color10  #3e8fb0

# yellow
color3   #f6c177
color11  #f6c177

# blue
color4   #9ccfd8
color12  #9ccfd8

# magenta
color5   #c4a7e7
color13  #c4a7e7

# cyan
color6   #ea9a97
color14  #ea9a97

# white
color7   #c8c8e5
color15  #c8c8e5

# Extended theme settings
scrollbar_handle_color    #c8c8e5
active_border_color       #393552
inactive_border_color     #393552
tab_bar_margin_color      #232136
tab_bar_background        #232136
active_tab_background     #232136
inactive_tab_background   #232136
tab_title_template        "{fmt.fg._393552}{fmt.bg._232136}{fmt.fg._c8c8e5}{fmt.bg._393552} {title[:12]} {fmt.fg._393552}{fmt.bg._232136}{fmt.bg._232136} "
active_tab_title_template "{fmt.fg._c4a7e7}{fmt.bg._232136}{fmt.fg._232136}{fmt.bg._c4a7e7}{fmt.bold} {title[:12]} {fmt.fg._c4a7e7}{fmt.bg._232136}{fmt.bg._232136} "
